name: Build PC package

on: [ push, pull_request, workflow_dispatch ]

# written referencing Kethen's RemoteJoyLite fork

jobs:
  build_pkg:
    runs-on: ubuntu-22.04
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Set env vars
      run: |
        echo "sha_name=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_ENV
        echo "PSPDEV=${GITHUB_WORKSPACE}/pspdev" >> $GITHUB_ENV
        echo "${GITHUB_WORKSPACE}/pspdev/bin:${GITHUB_WORKSPACE}/llvm-mingw-20241217-ucrt-ubuntu-20.04-x86_64/bin" >> $GITHUB_PATH

    - name: Install packages
      run: |
        sudo apt update
        sudo apt install -y make xz-utils gcc

    - name: Download PSP SDK
      run: |
        curl -sL https://github.com/pspdev/pspdev/releases/download/v20240701/pspdev-ubuntu-latest-x86_64.tar.gz | tar xvz -C ./

    - name: Download llvm-mingw-w64
      run: |
        curl -sL https://github.com/mstorsjo/llvm-mingw/releases/download/20241217/llvm-mingw-20241217-ucrt-ubuntu-20.04-x86_64.tar.xz | xz -d | tar -C ./ -xv

    - name: Build PSP
      run: |
        mkdir psp
        cd RemoteJoyLite_psp
        make
        mv RemoteJoyLiteDebug.prx ../psp/RemoteJoyLiteDebug.prx
        make clean
        make RELEASE=1
        mv RemoteJoyLite.prx ../psp/RemoteJoyLite.prx
        cd ..

    - name: Build PC 32 bit JA
      run: |
        mkdir x86
        cd RemoteJoyLite_pc
        make ARCH=x86 CPPC=i686-w64-mingw32-g++ WINDRES=i686-w64-mingw32-windres LANGUAGE=LANG_JA
        mv RemoteJoyLite.exe ../x86/RemoteJoyLite_JA_32.exe
        cp libusb0_x86.dll ../x86/libusb0.dll
        cp d3dx9_43_x86.dll ../x86/d3dx9_43.dll
        make clean
        cd ..

    - name: Build PC 32 bit EN
      run: |
        cd RemoteJoyLite_pc
        make ARCH=x86 CPPC=i686-w64-mingw32-g++ WINDRES=i686-w64-mingw32-windres LANGUAGE=LANG_EN
        mv RemoteJoyLite.exe ../x86/RemoteJoyLite_EN_32.exe
        make clean
        cd ..

    - name: Build PC 64 bit JA
      run: |
        mkdir x64
        cd RemoteJoyLite_pc
        make ARCH=x64 CPPC=x86_64-w64-mingw32-g++ WINDRES=x86_64-w64-mingw32-windres LANGUAGE=LANG_JA
        mv RemoteJoyLite.exe ../x64/RemoteJoyLite_JA_64.exe
        cp libusb0_x64.dll ../x64/libusb0.dll
        cp d3dx9_43_x64.dll ../x64/d3dx9_43.dll
        make clean
        cd ..

    - name: Build PC 64 bit EN
      run: |
        cd RemoteJoyLite_pc
        make ARCH=x64 CPPC=x86_64-w64-mingw32-g++ WINDRES=x86_64-w64-mingw32-windres LANGUAGE=LANG_EN
        mv RemoteJoyLite.exe ../x64/RemoteJoyLite_EN_64.exe
        make clean
        cd ..

    - name: Push package artifact
      uses: actions/upload-artifact@v4
      with:
        name: RemoteJoyLite_${{ env.sha_name }}
        path: |
          x86/RemoteJoyLite_JA_32.exe
          x86/RemoteJoyLite_EN_32.exe
          x64/RemoteJoyLite_JA_64.exe
          x64/RemoteJoyLite_EN_64.exe
          x86/libusb0.dll
          x86/d3dx9_43.dll
          x64/libusb0.dll
          x64/d3dx9_43.dll
          psp/RemoteJoyLite.prx
          psp/RemoteJoyLiteDebug.prx
        if-no-files-found: error
